/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CampaignsIdRouteImport } from './routes/campaigns/$id'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as TrackClickRouteImport } from './routes/track/click'
import { Route as TrackOpenRouteImport } from './routes/track/open'
import { Route as TrackUnsubscribeRouteImport } from './routes/track/unsubscribe'
import { Route as ApiWebhooksResendRouteImport } from './routes/api/webhooks/resend'
import { Route as ApiWorkerProcessQueueRouteImport } from './routes/api/worker/process-queue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackClickRoute = TrackClickRouteImport.update({
  id: '/track/click',
  path: '/track/click',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOpenRoute = TrackOpenRouteImport.update({
  id: '/track/open',
  path: '/track/open',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackUnsubscribeRoute = TrackUnsubscribeRouteImport.update({
  id: '/track/unsubscribe',
  path: '/track/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksResendRoute = ApiWebhooksResendRouteImport.update({
  id: '/api/webhooks/resend',
  path: '/api/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkerProcessQueueRoute = ApiWorkerProcessQueueRouteImport.update({
  id: '/api/worker/process-queue',
  path: '/api/worker/process-queue',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/track/click': typeof TrackClickRoute
  '/track/open': typeof TrackOpenRoute
  '/track/unsubscribe': typeof TrackUnsubscribeRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/api/worker/process-queue': typeof ApiWorkerProcessQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/track/click': typeof TrackClickRoute
  '/track/open': typeof TrackOpenRoute
  '/track/unsubscribe': typeof TrackUnsubscribeRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/api/worker/process-queue': typeof ApiWorkerProcessQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/track/click': typeof TrackClickRoute
  '/track/open': typeof TrackOpenRoute
  '/track/unsubscribe': typeof TrackUnsubscribeRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/api/worker/process-queue': typeof ApiWorkerProcessQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leads'
    | '/login'
    | '/settings'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/track/click'
    | '/track/open'
    | '/track/unsubscribe'
    | '/api/webhooks/resend'
    | '/api/worker/process-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leads'
    | '/login'
    | '/settings'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/track/click'
    | '/track/open'
    | '/track/unsubscribe'
    | '/api/webhooks/resend'
    | '/api/worker/process-queue'
  id:
    | '__root__'
    | '/'
    | '/leads'
    | '/login'
    | '/settings'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/track/click'
    | '/track/open'
    | '/track/unsubscribe'
    | '/api/webhooks/resend'
    | '/api/worker/process-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  TrackClickRoute: typeof TrackClickRoute
  TrackOpenRoute: typeof TrackOpenRoute
  TrackUnsubscribeRoute: typeof TrackUnsubscribeRoute
  ApiWebhooksResendRoute: typeof ApiWebhooksResendRoute
  ApiWorkerProcessQueueRoute: typeof ApiWorkerProcessQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/click': {
      id: '/track/click'
      path: '/track/click'
      fullPath: '/track/click'
      preLoaderRoute: typeof TrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/open': {
      id: '/track/open'
      path: '/track/open'
      fullPath: '/track/open'
      preLoaderRoute: typeof TrackOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/unsubscribe': {
      id: '/track/unsubscribe'
      path: '/track/unsubscribe'
      fullPath: '/track/unsubscribe'
      preLoaderRoute: typeof TrackUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/resend': {
      id: '/api/webhooks/resend'
      path: '/api/webhooks/resend'
      fullPath: '/api/webhooks/resend'
      preLoaderRoute: typeof ApiWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker/process-queue': {
      id: '/api/worker/process-queue'
      path: '/api/worker/process-queue'
      fullPath: '/api/worker/process-queue'
      preLoaderRoute: typeof ApiWorkerProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  TrackClickRoute: TrackClickRoute,
  TrackOpenRoute: TrackOpenRoute,
  TrackUnsubscribeRoute: TrackUnsubscribeRoute,
  ApiWebhooksResendRoute: ApiWebhooksResendRoute,
  ApiWorkerProcessQueueRoute: ApiWorkerProcessQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
