/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as EventsRouteImport } from './routes/events'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CampaignsIdRouteImport } from './routes/campaigns/$id'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as TrackClickRouteImport } from './routes/track/click'
import { Route as TrackOpenRouteImport } from './routes/track/open'
import { Route as TrackUnsubscribeRouteImport } from './routes/track/unsubscribe'
import { Route as ApiPublicCronProcessQueueRouteImport } from './routes/api/public/cron/process-queue'
import { Route as ApiPublicWebhooksResendRouteImport } from './routes/api/public/webhooks/resend'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackClickRoute = TrackClickRouteImport.update({
  id: '/track/click',
  path: '/track/click',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOpenRoute = TrackOpenRouteImport.update({
  id: '/track/open',
  path: '/track/open',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackUnsubscribeRoute = TrackUnsubscribeRouteImport.update({
  id: '/track/unsubscribe',
  path: '/track/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronProcessQueueRoute =
  ApiPublicCronProcessQueueRouteImport.update({
    id: '/api/public/cron/process-queue',
    path: '/api/public/cron/process-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksResendRoute = ApiPublicWebhooksResendRouteImport.update({
  id: '/api/public/webhooks/resend',
  path: '/api/public/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/events': typeof EventsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/track/click': typeof TrackClickRoute
  '/track/open': typeof TrackOpenRoute
  '/track/unsubscribe': typeof TrackUnsubscribeRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/events': typeof EventsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/track/click': typeof TrackClickRoute
  '/track/open': typeof TrackOpenRoute
  '/track/unsubscribe': typeof TrackUnsubscribeRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/events': typeof EventsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/track/click': typeof TrackClickRoute
  '/track/open': typeof TrackOpenRoute
  '/track/unsubscribe': typeof TrackUnsubscribeRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/diagnostics'
    | '/events'
    | '/leads'
    | '/login'
    | '/settings'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/track/click'
    | '/track/open'
    | '/track/unsubscribe'
    | '/api/public/cron/process-queue'
    | '/api/public/webhooks/resend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/diagnostics'
    | '/events'
    | '/leads'
    | '/login'
    | '/settings'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/track/click'
    | '/track/open'
    | '/track/unsubscribe'
    | '/api/public/cron/process-queue'
    | '/api/public/webhooks/resend'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/diagnostics'
    | '/events'
    | '/leads'
    | '/login'
    | '/settings'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/track/click'
    | '/track/open'
    | '/track/unsubscribe'
    | '/api/public/cron/process-queue'
    | '/api/public/webhooks/resend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  EventsRoute: typeof EventsRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  TrackClickRoute: typeof TrackClickRoute
  TrackOpenRoute: typeof TrackOpenRoute
  TrackUnsubscribeRoute: typeof TrackUnsubscribeRoute
  ApiPublicCronProcessQueueRoute: typeof ApiPublicCronProcessQueueRoute
  ApiPublicWebhooksResendRoute: typeof ApiPublicWebhooksResendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/click': {
      id: '/track/click'
      path: '/track/click'
      fullPath: '/track/click'
      preLoaderRoute: typeof TrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/open': {
      id: '/track/open'
      path: '/track/open'
      fullPath: '/track/open'
      preLoaderRoute: typeof TrackOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/unsubscribe': {
      id: '/track/unsubscribe'
      path: '/track/unsubscribe'
      fullPath: '/track/unsubscribe'
      preLoaderRoute: typeof TrackUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/process-queue': {
      id: '/api/public/cron/process-queue'
      path: '/api/public/cron/process-queue'
      fullPath: '/api/public/cron/process-queue'
      preLoaderRoute: typeof ApiPublicCronProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/resend': {
      id: '/api/public/webhooks/resend'
      path: '/api/public/webhooks/resend'
      fullPath: '/api/public/webhooks/resend'
      preLoaderRoute: typeof ApiPublicWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  EventsRoute: EventsRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  TrackClickRoute: TrackClickRoute,
  TrackOpenRoute: TrackOpenRoute,
  TrackUnsubscribeRoute: TrackUnsubscribeRoute,
  ApiPublicCronProcessQueueRoute: ApiPublicCronProcessQueueRoute,
  ApiPublicWebhooksResendRoute: ApiPublicWebhooksResendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
